### ISSUE TITLE
Try three fits for tie line

### ISSUE THREAD

**Issue by alchemyst** [Mistress/DWPM-Mixing-Rule---Binary-Systems#4]
For each tie line attempt, try an optimisation with x1=0 and x2 free, x2 = 1 and x1 free and then with both free.

**Comment by Mistress** [comment]
decreased tolerance for optimizer and included [0.0001, 0.999] as an initial value for multistart method --> seeing as the reported phase compositions may be in the order of 1e-5, but never exactly equal to 0.
